name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@3.2.0          
        with:        
          root_file: |
            - "report/ijcai24.tex"
            - "report/ijcai24.bib"
            - "report/ijcai24.sty"
            - "report/named.bst"
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: ijcai24.pdf
