name: Test Github Action
on:
  push:
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        texlive_version: [2022, 2023, latest]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile basic LaTeX document
        uses: ./
        with:
          texlive_version: ${{ matrix.texlive_version }}
          root_file: ijcai24.tex
          working_directory: report/
      - name: Compile multiple LaTeX documents
        uses: ./
        with:
          texlive_version: ${{ matrix.texlive_version }}
          root_file: |
            ijcai24.tex
          working_directory: report/
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ijcai24
          path: report
