name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: report/
          root_file: ijcai24.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          working_directory: report/
          name: PDF
          path: ijcai24.pdf
